version: '3.5'

services:
  thoraverifier:
    container_name: thoraverifier_container
    image: giangbb/thora-contract-verifier:1.0
    volumes:
      - ./thoraverifier.env.testnet:/home/app/environments/.env
    env_file:
      - thoraverifier.env.testnet
    ports:
      - "5555:5555"
    networks:
      - thoraepl-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -S http://10.61.60.107:5555/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  thoraepl-network:
    name: thoraepl