version: '3.5'

services:
  thoraverifier:
    container_name: thoraverifier_container
    image: giangbb/thora-contract-verifier:1.0
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      NODE_ENV: ${NODE_ENV}
      IPFS_GATEWAY: ${IPFS_GATEWAY}
      STORING_MODE: ${STORING_MODE}
      REPOSITORY_PATH: ${REPOSITORY_PATH}
      SOLC_REPO: ${SOLC_REPO}
      SOLJSON_REPO: ${SOLJSON_REPO}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5555:5555"
    networks:
      - thoraepl-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -S http://10.61.60.107:5555/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  thoraepl-network:
    name: thoraepl